version: '2'
services:
  ipfs:
    image: ipfs/go-ipfs:master
    working_dir: /home/kyle/.ipfs/
    hostname: ipfs_host
    volumes:
    - "./export:/export"
    - "./data/ipfs:/data/ipfs"
    - "./assets:/assets"
    ports:
    - "5001:5001"
    - "4001:4001"
    - "8080:8080"
